// Puntos de interés REALES en la línea del eclipse
// Solo incluye lugares que están dentro o muy cerca de la franja de totalidad

export type POICategory = "monumento" | "natural" | "religioso" | "museo" | "mirador"

export interface PointOfInterest {
  id: string
  name: string
  lat: number
  lng: number
  category: POICategory
  description: string
  photoTip: string
  inTotality: boolean
  duracionTotalidad?: string
}

export const pointsOfInterest2026: PointOfInterest[] = [
  // GALICIA
  {
    id: "torre-hercules",
    name: "Torre de Hércules",
    lat: 43.3857,
    lng: -8.4066,
    category: "monumento",
    description: "Faro romano del siglo I, Patrimonio de la Humanidad. El más antiguo en funcionamiento.",
    photoTip: "Totalidad ~1m 20s. Sol a 12°. La corona solar detrás de la torre será icónica.",
    inTotality: true,
    duracionTotalidad: "1m 20s",
  },
  {
    id: "catedral-santiago",
    name: "Catedral de Santiago",
    lat: 42.8805,
    lng: -8.5446,
    category: "religioso",
    description: "Meta del Camino de Santiago. Fachada del Obradoiro.",
    photoTip: "Totalidad ~1m 41s. Las torres silueteadas contra el cielo oscurecido.",
    inTotality: true,
    duracionTotalidad: "1m 41s",
  },
  {
    id: "playa-catedrales",
    name: "Playa de las Catedrales",
    lat: 43.5536,
    lng: -7.1572,
    category: "natural",
    description: "Arcos naturales de 30m de altura en la costa de Lugo.",
    photoTip: "Totalidad ~1m 35s. Sol entre los arcos de roca al atardecer.",
    inTotality: true,
    duracionTotalidad: "1m 35s",
  },
  // ASTURIAS
  {
    id: "cementerio-luarca",
    name: "Cementerio de Luarca",
    lat: 43.5448,
    lng: -6.5361,
    category: "monumento",
    description: "Uno de los cementerios más bellos del mundo, con vistas al mar. Justo en la línea central.",
    photoTip: "Totalidad ~1m 49s. Máxima duración en la península. Vistas espectaculares al Cantábrico.",
    inTotality: true,
    duracionTotalidad: "1m 49s",
  },
  {
    id: "covadonga",
    name: "Lagos de Covadonga",
    lat: 43.2714,
    lng: -4.9856,
    category: "natural",
    description: "Lagos glaciares de Enol y Ercina en los Picos de Europa.",
    photoTip: "Totalidad ~1m 40s. Reflejo del eclipse en los lagos a 1000m de altitud.",
    inTotality: true,
    duracionTotalidad: "1m 40s",
  },
  {
    id: "santa-maria-naranco",
    name: "Santa María del Naranco",
    lat: 43.3833,
    lng: -5.8667,
    category: "religioso",
    description: "Joya del prerrománico asturiano del siglo IX. Patrimonio de la Humanidad.",
    photoTip: "Totalidad ~1m 44s. Arquitectura del siglo IX con el eclipse de fondo.",
    inTotality: true,
    duracionTotalidad: "1m 44s",
  },
  // PAÍS VASCO
  {
    id: "gaztelugatxe",
    name: "San Juan de Gaztelugatxe",
    lat: 43.4452,
    lng: -2.7833,
    category: "religioso",
    description: "Ermita sobre islote con 241 escalones. Famosa por Juego de Tronos.",
    photoTip: "Totalidad ~1m 45s. Silueta del islote contra el cielo oscurecido sobre el mar.",
    inTotality: true,
    duracionTotalidad: "1m 45s",
  },
  {
    id: "guggenheim",
    name: "Museo Guggenheim",
    lat: 43.2687,
    lng: -2.934,
    category: "museo",
    description: "Obra maestra de Frank Gehry. Titanio que refleja la luz.",
    photoTip: "Totalidad ~1m 47s. Las superficies metálicas capturarán la luz de la corona.",
    inTotality: true,
    duracionTotalidad: "1m 47s",
  },
  {
    id: "puente-vizcaya",
    name: "Puente Colgante de Vizcaya",
    lat: 43.3233,
    lng: -3.0175,
    category: "monumento",
    description: "Primer puente transbordador del mundo (1893). Patrimonio de la Humanidad.",
    photoTip: "Totalidad ~1m 45s. Estructura metálica silueteada contra la corona solar.",
    inTotality: true,
    duracionTotalidad: "1m 45s",
  },
  {
    id: "peine-viento",
    name: "El Peine del Viento",
    lat: 43.3103,
    lng: -2.0058,
    category: "monumento",
    description: "Esculturas de Eduardo Chillida integradas en las rocas de San Sebastián.",
    photoTip: "Totalidad ~1m 32s. Formas abstractas con el mar y cielo del eclipse.",
    inTotality: true,
    duracionTotalidad: "1m 32s",
  },
  // CASTILLA Y LEÓN
  {
    id: "canon-rio-lobos",
    name: "Cañón del Río Lobos",
    lat: 41.7416,
    lng: -3.0736,
    category: "natural",
    description: "Espectacular cañón calizo en Soria/Burgos. La línea central pasa exactamente por aquí.",
    photoTip: "Totalidad ~1m 45s. La Ermita de San Bartolomé en el fondo del cañón con el eclipse.",
    inTotality: true,
    duracionTotalidad: "1m 45s",
  },
  {
    id: "santo-domingo-silos",
    name: "Monasterio de Silos",
    lat: 41.9633,
    lng: -3.4208,
    category: "religioso",
    description: "Joya del románico famosa por su claustro y canto gregoriano. Muy cerca de la centralidad.",
    photoTip: "Totalidad ~1m 44s. El ciprés del claustro bajo la luz de la totalidad.",
    inTotality: true,
    duracionTotalidad: "1m 44s",
  },
  {
    id: "catedral-burgos",
    name: "Catedral de Burgos",
    lat: 42.3406,
    lng: -3.7042,
    category: "religioso",
    description: "Catedral gótica del siglo XIII. Patrimonio de la Humanidad.",
    photoTip: "Totalidad ~1m 44s. Agujas góticas contra el cielo oscurecido.",
    inTotality: true,
    duracionTotalidad: "1m 44s",
  },
  {
    id: "catedral-leon",
    name: "Catedral de León",
    lat: 42.5995,
    lng: -5.567,
    category: "religioso",
    description: "La 'Pulchra Leonina', famosa por sus vidrieras medievales.",
    photoTip: "Totalidad ~1m 44s. Vidrieras con la luz especial del eclipse.",
    inTotality: true,
    duracionTotalidad: "1m 44s",
  },
  // LA RIOJA
  {
    id: "san-millan",
    name: "Monasterio de San Millán",
    lat: 42.3267,
    lng: -2.8686,
    category: "religioso",
    description: "Cuna del castellano escrito. Patrimonio de la Humanidad.",
    photoTip: "Totalidad ~1m 25s. El monasterio románico con el eclipse.",
    inTotality: true,
    duracionTotalidad: "1m 25s",
  },
  // CASTILLA-LA MANCHA
  {
    id: "castillo-siguenza",
    name: "Castillo de Sigüenza",
    lat: 41.0652,
    lng: -2.6416,
    category: "monumento",
    description: "Imponente castillo medieval (Parador) en Guadalajara. Cerca de la línea central.",
    photoTip: "Totalidad ~1m 38s. Las torres almenadas recortadas contra el eclipse.",
    inTotality: true,
    duracionTotalidad: "1m 38s",
  },
  // ARAGÓN
  {
    id: "basilica-pilar",
    name: "Basílica del Pilar",
    lat: 41.6566,
    lng: -0.8789,
    category: "religioso",
    description: "Santuario mariano con 11 cúpulas sobre el río Ebro.",
    photoTip: "Totalidad ~1m 06s. Reflejo en el Ebro durante la totalidad. Sol muy bajo (4°).",
    inTotality: true,
    duracionTotalidad: "1m 06s",
  },
  {
    id: "aljaferia",
    name: "Palacio de la Aljafería",
    lat: 41.6561,
    lng: -0.8967,
    category: "monumento",
    description: "Palacio islámico del siglo XI, uno de los mejor conservados de España.",
    photoTip: "Totalidad ~1m 06s. Torre del Trovador contra el eclipse.",
    inTotality: true,
    duracionTotalidad: "1m 06s",
  },
  // COMUNIDAD VALENCIANA
  {
    id: "castillo-peniscola",
    name: "Castillo de Peñíscola",
    lat: 40.3585,
    lng: 0.4074,
    category: "monumento",
    description: "Fortaleza templaria junto al mar. La línea central pasa sobre el castillo.",
    photoTip: "Totalidad ~1m 15s. El castillo del Papa Luna y el mar Mediterráneo en oscuridad.",
    inTotality: true,
    duracionTotalidad: "1m 15s",
  },
  // BALEARES
  {
    id: "catedral-palma",
    name: "Catedral de Palma",
    lat: 39.5674,
    lng: 2.6483,
    category: "religioso",
    description: "Catedral gótica frente al mar. El eclipse termina aquí al atardecer.",
    photoTip: "Totalidad ~1m 36s. Sol rozando el horizonte (2°) junto a la catedral.",
    inTotality: true,
    duracionTotalidad: "1m 36s",
  },
  {
    id: "pont-den-gil",
    name: "Pont d'en Gil",
    lat: 39.9908,
    lng: 3.8261,
    category: "natural",
    description: "Arco natural de roca sobre el mar en Menorca.",
    photoTip: "Totalidad ~55s. Sol MUY bajo (1°). El sol eclipsado a través del arco.",
    inTotality: true,
    duracionTotalidad: "0m 55s",
  },
  {
    id: "naveta-tudons",
    name: "Naveta des Tudons",
    lat: 40.0039,
    lng: 3.8917,
    category: "monumento",
    description: "Tumba megalítica de 3.400 años, el edificio más antiguo de Europa.",
    photoTip: "Totalidad ~55s. Silueta prehistórica contra el cielo del eclipse.",
    inTotality: true,
    duracionTotalidad: "0m 55s",
  },
  {
    id: "monte-toro",
    name: "Monte Toro",
    lat: 39.9872,
    lng: 4.1122,
    category: "mirador",
    description: "Punto más alto de Menorca (358m) con santuario y vistas 360°.",
    photoTip: "Totalidad ~55s. Ver la sombra lunar aproximarse desde el horizonte oeste.",
    inTotality: true,
    duracionTotalidad: "0m 55s",
  },
]

export const pointsOfInterest2027: PointOfInterest[] = [
  // CÁDIZ
  {
    id: "baelo-claudia",
    name: "Baelo Claudia",
    lat: 36.0898,
    lng: -5.7735,
    category: "monumento",
    description: "Antigua ciudad romana en la playa de Bolonia. Una de las mejores vistas del eclipse.",
    photoTip: "Totalidad ~4m 30s. Ruinas romanas con el sol alto (40°) y África de fondo.",
    inTotality: true,
    duracionTotalidad: "4m 30s",
  },
  {
    id: "castillo-tarifa",
    name: "Castillo de Guzmán el Bueno",
    lat: 36.0125,
    lng: -5.6028,
    category: "monumento",
    description: "Fortaleza califal en el punto más meridional de Europa continental.",
    photoTip: "Totalidad ~4m 40s. Murallas medievales frente al Estrecho oscurecido.",
    inTotality: true,
    duracionTotalidad: "4m 40s",
  },
  {
    id: "faro-camarinal",
    name: "Faro de Camarinal",
    lat: 36.0934,
    lng: -5.8087,
    category: "mirador",
    description: "Faro sobre antigua torre vigía con vistas espectaculares del océano.",
    photoTip: "Totalidad ~4m 35s. Silueta del faro con el cielo negro a mediodía.",
    inTotality: true,
    duracionTotalidad: "4m 35s",
  },
  // GIBRALTAR
  {
    id: "rock-gibraltar",
    name: "Peñón de Gibraltar",
    lat: 36.1447,
    lng: -5.3526,
    category: "natural",
    description: "La famosa roca calcárea. Vistas únicas desde la cima.",
    photoTip: "Totalidad ~4m 25s. Panorámica de 3 continentes bajo la sombra lunar.",
    inTotality: true,
    duracionTotalidad: "4m 25s",
  },
  {
    id: "europa-point",
    name: "Punta de Europa",
    lat: 36.1096,
    lng: -5.3463,
    category: "mirador",
    description: "Extremo sur de Gibraltar, con el faro y la mezquita.",
    photoTip: "Totalidad ~4m 28s. Faro y mar con Marruecos visiblemente oscurecido.",
    inTotality: true,
    duracionTotalidad: "4m 28s",
  },
  // MÁLAGA
  {
    id: "castillo-duquesa",
    name: "Castillo de la Duquesa",
    lat: 36.3506,
    lng: -5.2306,
    category: "monumento",
    description: "Fortaleza costera del siglo XVIII en Manilva.",
    photoTip: "Totalidad ~3m 50s. Castillo junto al mar en plena Costa del Sol.",
    inTotality: true,
    duracionTotalidad: "3m 50s",
  },
  // CEUTA
  {
    id: "murallas-reales-ceuta",
    name: "Murallas Reales de Ceuta",
    lat: 35.8887,
    lng: -5.3168,
    category: "monumento",
    description: "Conjunto monumental renacentista único con foso navegable.",
    photoTip: "Totalidad ~4m 45s. Arquitectura militar con reflejos en el foso.",
    inTotality: true,
    duracionTotalidad: "4m 45s",
  },
  {
    id: "monte-hacho",
    name: "Monte Hacho",
    lat: 35.8972,
    lng: -5.2950,
    category: "mirador",
    description: "Uno de los posibles Pilares de Hércules, vistas dominantes.",
    photoTip: "Totalidad ~4m 48s. Vista elevada de Ceuta y el Estrecho en eclipse.",
    inTotality: true,
    duracionTotalidad: "4m 48s",
  },
  // MELILLA
  {
    id: "melilla-vieja",
    name: "Melilla la Vieja",
    lat: 35.2941,
    lng: -2.9333,
    category: "monumento",
    description: "Ciudadela fortificada sobre el mar, 'El Pueblo'.",
    photoTip: "Totalidad ~4m 40s. Murallas fenicias y renacentistas bajo la corona solar.",
    inTotality: true,
    duracionTotalidad: "4m 40s",
  },
]

export const pointsOfInterest2028: PointOfInterest[] = [
  // HUELVA
  {
    id: "monasterio-rabida",
    name: "Monasterio de La Rábida",
    lat: 37.2091,
    lng: -6.9272,
    category: "religioso",
    description: "Lugar colombino por excelencia. Anularidad visible.",
    photoTip: "Anularidad ~7m. El anillo de fuego sobre el monasterio histórico.",
    inTotality: true, // Es anularidad en realidad
    duracionTotalidad: "7m 05s",
  },
  {
    id: "muelle-tinto",
    name: "Muelle del Tinto",
    lat: 37.2575,
    lng: -6.9385,
    category: "monumento",
    description: "Antiguo embarcadero de mineral inglés sobre el río Odiel.",
    photoTip: "Anularidad ~7m. Estructura de hierro silueteada con el sol bajo.",
    inTotality: true,
    duracionTotalidad: "7m 05s",
  },
  // SEVILLA
  {
    id: "giralda",
    name: "La Giralda",
    lat: 37.3861,
    lng: -5.9925,
    category: "monumento",
    description: "Icono de Sevilla. La anularidad pasará justo por encima.",
    photoTip: "Anularidad ~7m 10s. El anillo de fuego junto al Giraldillo al atardecer.",
    inTotality: true,
    duracionTotalidad: "7m 10s",
  },
  {
    id: "plaza-espana",
    name: "Plaza de España",
    lat: 37.3772,
    lng: -5.9869,
    category: "monumento",
    description: "Conjunto arquitectónico monumental del Parque de María Luisa.",
    photoTip: "Anularidad ~7m 10s. Reflejos en el canal y puentes con luz dorada extrema.",
    inTotality: true,
    duracionTotalidad: "7m 10s",
  },
  // CÓRDOBA
  {
    id: "mezquita-cordoba",
    name: "Mezquita de Córdoba",
    lat: 37.8789,
    lng: -4.7794,
    category: "religioso",
    description: "Patrimonio de la Humanidad. Espectáculo único.",
    photoTip: "Anularidad ~6m 50s. Arcos y palmeras con el sol anular.",
    inTotality: true,
    duracionTotalidad: "6m 50s",
  },
  {
    id: "puente-romano",
    name: "Puente Romano de Córdoba",
    lat: 37.8763,
    lng: -4.7778,
    category: "monumento",
    description: "Puente histórico sobre el Guadalquivir con vistas a la Mezquita.",
    photoTip: "Anularidad ~6m 50s. Vista clásica del puente con el sol anular de fondo.",
    inTotality: true,
    duracionTotalidad: "6m 50s",
  },
  // JAÉN (Úbeda y Baeza están cerca del centro)
  {
    id: "plaza-vazquez-molina",
    name: "Plaza Vázquez de Molina (Úbeda)",
    lat: 38.0084,
    lng: -3.3678,
    category: "monumento",
    description: "Joya del Renacimiento español. Patrimonio de la Humanidad.",
    photoTip: "Anularidad ~7m. La Sacra Capilla del Salvador bajo el anillo de fuego.",
    inTotality: true,
    duracionTotalidad: "7m 00s",
  },
  // CASTILLA-LA MANCHA / ALBACETE
  {
    id: "castillo-almansa",
    name: "Castillo de Almansa",
    lat: 38.8706,
    lng: -1.0975,
    category: "monumento",
    description: "Impresionante fortaleza sobre el cerro del Águila.",
    photoTip: "Anularidad ~6m 30s. Silueta espectacular del castillo con el sol bajo.",
    inTotality: true,
    duracionTotalidad: "6m 30s",
  },
  // VALENCIA
  {
    id: "ciudad-artes",
    name: "Ciudad de las Artes",
    lat: 39.4546,
    lng: -0.3503,
    category: "monumento",
    description: "Arquitectura futurista de Calatrava.",
    photoTip: "Anularidad ~5m 30s. Formas modernas recortadas contra el anillo de fuego.",
    inTotality: true,
    duracionTotalidad: "5m 30s",
  },
  {
    id: "albufera-valencia",
    name: "La Albufera",
    lat: 39.3333,
    lng: -0.3667,
    category: "natural",
    description: "Parque natural y laguna costera famosa por sus atardeceres.",
    photoTip: "Anularidad ~5m 45s. Puesta de sol ANULAR reflejada en el agua. Único.",
    inTotality: true,
    duracionTotalidad: "5m 45s",
  },
  // IBIZA
  {
    id: "dalt-vila",
    name: "Dalt Vila",
    lat: 38.9068,
    lng: 1.4362,
    category: "monumento",
    description: "Casco antiguo fortificado de Ibiza.",
    photoTip: "Anularidad ~4m. Puesta de sol anular sobre el mar.",
    inTotality: true,
    duracionTotalidad: "4m 00s",
  },
  {
    id: "es-vedra",
    name: "Es Vedrà",
    lat: 38.8683,
    lng: 1.2269,
    category: "natural",
    description: "Islote místico y magnético frente a la costa suroeste de Ibiza.",
    photoTip: "Anularidad ~4m 30s. El anillo de fuego poniéndose tras la roca icónica.",
    inTotality: true,
    duracionTotalidad: "4m 30s",
  },
  // MALLORCA
  {
    id: "catedral-palma-2028",
    name: "Catedral de Palma",
    lat: 39.5674,
    lng: 2.6483,
    category: "religioso",
    description: "La Seu gótica frente al mar. El eclipse ocurre justo en la puesta de sol.",
    photoTip: "Anularidad ~3m. Sol rozando el horizonte (1°) junto a la catedral.",
    inTotality: true,
    duracionTotalidad: "3m 00s",
  }
]

// Mapas de POIs por año
export const poisByYear: Record<string, PointOfInterest[]> = {
  "2026": pointsOfInterest2026,
  "2027": pointsOfInterest2027,
  "2028": pointsOfInterest2028,
}

// Mantener compatibilidad por defecto
export const pointsOfInterest = pointsOfInterest2026

export const categoryLabels: Record<POICategory, string> = {
  monumento: "Monumento",
  natural: "Natural",
  religioso: "Religioso",
  museo: "Museo",
  mirador: "Mirador",
}

export const categoryColors: Record<POICategory, string> = {
  monumento: "#f59e0b",
  natural: "#10b981",
  religioso: "#ec4899",
  museo: "#8b5cf6",
  mirador: "#06b6d4",
}
